version: '3.3'


services:

  ca:
    container_name: iot-tunnel-ca
    build: ./ca
    restart: on-failure
    ports:
      - 8888:8888
    networks:
      - default
    volumes:
      - common:/etc/common
      - ca-pki:/etc/cfssl/ca/pki
      - log:/var/log
    depends_on:
      - database
    env_file:
      - .env

  database:
    container_name: iot-tunnel-database
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - ./ca/config/init-cert-store.sql:/docker-entrypoint-initdb.d/init-cert-store.sql
      - default-database:/var/lib/postgresql/data
    env_file:
      - .env

  ovpn-server:
    container_name: iot-tunnel-ovpn-server
    build: ./ovpn-server
    restart: on-failure
    ports:
      - 443:443
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.rp_filter=0
    networks:
      - default
    depends_on:
      - ca
    volumes:
      - common:/etc/common
      - ovpn-pki:/etc/openvpn/server/pki
      - log:/var/log
    env_file:
      - .env

  management-service:
    container_name: iot-tunnel-management-service
    build: ./management-service
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - default
    depends_on:
      - ca
      - ovpn-server
    volumes:
      - common:/etc/common
      - log:/var/log
    env_file:
      - .env


networks:
  default:
    name: iot-tunnel-default-network
    driver: bridge
    ipam:
      config:
        - subnet: $SERVER_END_NETWORK_CIDR


volumes:
  common:
    name: iot-tunnel-common-volume
  ca-pki:
    name: iot-tunnel-ca-pki-volume
  default-database:
    name: iot-tunnel-ca-default-database
  ovpn-pki:
    name: iot-tunnel-ovpn-pki-volume
  log:
    name: iot-tunnel-log-volume
