version: '3.3'


services:

  ca:
    container_name: iot-tunnel-ca
    build: ./ca
    ports:
      - 8888:8888
    networks:
      - default
    volumes:
      - common:/etc/common/
      - ca-pki:/etc/cfssl/ca/pki

  ovpn-server:
    container_name: iot-tunnel-ovpn-server
    build: ./ovpn-server
    ports:
      - 443:443
    cap_add:
      - NET_ADMIN
    networks:
      - default
    depends_on:
      - ca
    volumes:
      - common:/etc/common/
      - ovpn-pki:/etc/openvpn/server/pki

  client-configurer:
    container_name: iot-tunnel-client-configurer
    build: ./client
    command: ./entrypoint.sh
    networks:
      - default
    depends_on:
      - ca
      - ovpn-server
    volumes:
      - common:/etc/common

  test-service:
    container_name: iot-tunnel-test-seervice
    image: ubuntu:latest
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    networks:
      - default
    depends_on:
      - ca
      - ovpn-server
    volumes:
      - common:/etc/common


networks:
  default:
    name: iot-tunnel-default-network

volumes:
  common:
    name: iot-tunnel-common-volume
  ca-pki:
    name: iot-tunnel-ca-pki
  ovpn-pki:
    name: iot-tunnel-ovpn-pki
