---

- hosts: servers
  become: yes
  tasks:

  - name: Update packages
    apt:
      update_cache: yes
  
  - name: Upgrade packages
    apt:
      upgrade: yes
  
  - name: Install OpenVPN
    apt:
      pkg:
      - golang-cfssl
      - openvpn
      - net-tools
      - ufw

  # configure firewall
    # configure before.rules
    

  # create local dir `cfssl`

  # create ca-config.json
  # create ca-csr.json
  # init CA with `cfssl gencert -initca ca-csr.json | cfssljson -bare ca -`
  # copy CA to its global dest `sudo cp ~/cfssl/ca.pem /usr/local/share/ca-certificates/ca.crt`
  # update ca certs locally `sudo update-ca-certificates`
  # copy CA to openvpn dest `sudo cp cfssl/ca.pem /etc/openvpn/server/ca.crt`

  # create server-scr.json
  # generate server cert and pk with `cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=server server-csr.json | cfssljson -bare server`
  # copy server cert to openvpn dest `sudo cp ~/cfssl/server.pem /etc/openvpn/server/server.crt`

  # generate TLS pre-shared key `cd ~/cfssl && openvpn --genkey --secret ta.key`
  # copy ta to openvpn dest `sudo cp ~/cfssl/ta.key /etc/openvpn/server`


