paths:
  open-vpn:
    client-config-directory: /etc/common/ccd
    ta-key: /etc/common/ta.key
  certificate-authority:
    ca-cert: /etc/common/ca.crt

endpoints:
  certificate-authority:
    new_cert: http://ca:8888/api/v1/cfssl/newcert

defaults:
  open-vpn:
    internal-network-address: ${OVPN_INTERNAL_NETWORK_ADDRESS}
    internal-network-mask: ${OVPN_INTERNAL_NETWORK_MASK}
    external-address: ${OVPN_EXTERNAL_IP_ADDRESS}
    external-port: ${OVPN_EXTERNAL_PORT}

spring:
  datasource:
    url: jdbc:postgresql://database:5432/default
    username: admin
    password: admin
  jpa:
    generate-ddl: true

server:
  port: ${MANAGEMENT_SERVICE_PORT}
